/*
SQLyog Community v12.2.1 (64 bit)
MySQL - 8.0.22 : Database - odonto
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`odonto` /*!40100 DEFAULT CHARACTER SET latin1 */ /*!80016 DEFAULT ENCRYPTION='N' */;

USE `odonto`;

/*Table structure for table `ope_clinica` */

DROP TABLE IF EXISTS `ope_clinica`;

CREATE TABLE `ope_clinica` (
  `IDCLINICA` int NOT NULL AUTO_INCREMENT,
  `DESC_CLINICA` varchar(100) DEFAULT NULL,
  `DIRECCION` varchar(80) DEFAULT NULL,
  `TELEFONO` varchar(20) DEFAULT NULL,
  `EMAIL` varchar(50) DEFAULT NULL,
  `ESTADO` char(1) DEFAULT 'A',
  `USU_ALTA` int DEFAULT NULL,
  `FEC_ALTA` datetime DEFAULT NULL,
  PRIMARY KEY (`IDCLINICA`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Data for the table `ope_clinica` */

insert  into `ope_clinica`(`IDCLINICA`,`DESC_CLINICA`,`DIRECCION`,`TELEFONO`,`EMAIL`,`ESTADO`,`USU_ALTA`,`FEC_ALTA`) values 
(1,'CENTRAL','','0','A','A',NULL,NULL);

/*Table structure for table `rh_persona` */

DROP TABLE IF EXISTS `rh_persona`;

CREATE TABLE `rh_persona` (
  `IDPERSONA` int NOT NULL,
  `NOMBRE` varchar(50) DEFAULT NULL,
  `APELLIDO` varchar(50) DEFAULT NULL,
  `CINRO` varchar(20) DEFAULT NULL,
  `TIPODOC` varchar(10) DEFAULT NULL,
  `IDCATEGORIA_PERSONA` int DEFAULT NULL COMMENT 'LO MANEJO COMO SI FUERA PERFIL',
  `DESC_CATEG_PERSONA` varchar(20) DEFAULT NULL,
  `RAZON_SOCIAL` varchar(100) DEFAULT NULL,
  `RUC` varchar(20) DEFAULT NULL,
  `DIRECCION` varchar(80) DEFAULT NULL,
  `EMAIL` varchar(80) DEFAULT NULL,
  `IDBARRIO` int DEFAULT NULL,
  `IDCIUDAD` int DEFAULT NULL,
  `TELFPARTICULAR` varchar(20) DEFAULT NULL,
  `TELFMOVIL` varchar(20) DEFAULT NULL,
  `IDCIUDADNAC` int DEFAULT NULL,
  `FECHANAC` date DEFAULT NULL,
  `SEXO` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'N',
  `RELIGION` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'N',
  `ESTADOCIVIL` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'N',
  `GRUPOSANGUINEO` varchar(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'N',
  `OBSERVACION` varchar(150) DEFAULT NULL,
  `FECHAALTA` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `FECULTMOMOV` timestamp NULL DEFAULT '0000-00-00 00:00:00',
  `FOTO` varchar(100) DEFAULT NULL,
  `USU_ALTA` int DEFAULT NULL,
  `USU_MOD` int DEFAULT NULL,
  `IDPAIS` int DEFAULT NULL,
  `TELEFPARTICULAR` varchar(15) DEFAULT NULL,
  `OCUPACION` varchar(50) DEFAULT NULL,
  `ANTECEDENTES` varchar(200) DEFAULT NULL,
  `EXPEDIENTE_CLINICO` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`IDPERSONA`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `rh_persona` */

insert  into `rh_persona`(`IDPERSONA`,`NOMBRE`,`APELLIDO`,`CINRO`,`TIPODOC`,`IDCATEGORIA_PERSONA`,`DESC_CATEG_PERSONA`,`RAZON_SOCIAL`,`RUC`,`DIRECCION`,`EMAIL`,`IDBARRIO`,`IDCIUDAD`,`TELFPARTICULAR`,`TELFMOVIL`,`IDCIUDADNAC`,`FECHANAC`,`SEXO`,`RELIGION`,`ESTADOCIVIL`,`GRUPOSANGUINEO`,`OBSERVACION`,`FECHAALTA`,`FECULTMOMOV`,`FOTO`,`USU_ALTA`,`USU_MOD`,`IDPAIS`,`TELEFPARTICULAR`,`OCUPACION`,`ANTECEDENTES`,`EXPEDIENTE_CLINICO`) values 
(0,'','Cliente Ocasional','000000','CI',4,'PACIENTE','(NO/DEFINIDO)','000000',NULL,NULL,0,0,NULL,NULL,0,'2021-11-24','N',NULL,NULL,NULL,NULL,'2021-11-26 10:10:47','0000-00-00 00:00:00',NULL,0,NULL,0,NULL,NULL,NULL,NULL),
(1,'','ROOT','000000','CI',1,'ADMINISTRADOR','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','N','N','N',NULL,'2021-11-26 12:29:05','0000-00-00 00:00:00',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(2,'LEO','PAREDES','93202','CI',4,'PACIENTE','LEO TORRES','101221-1','Abc','A',0,0,'','123456',0,'1995-01-01','M','','N','','','2021-12-10 09:39:09',NULL,'',1,0,0,'','','2021-12-10 9:39:9','N'),
(3,'Juan','Argaña','511890','CI',5,'MEDICO','Juan Argaña','5118890-1','a','a',0,0,'','012',0,'1990-01-01','M','','N','','','2021-12-11 11:38:37',NULL,'',1,0,0,'','','2021-12-11 11:38:37','N'),
(4,'Victor','Secret','75433','CI',3,'SECRETARIO','Victor Secret','75433-1','a','a',0,0,'','0',0,'1990-01-01','M','','N','','','2021-12-14 09:56:55',NULL,'',1,0,0,'','','2021-12-14 9:56:55','N'),
(5,'koke','gonzalez','14122021','CI',2,'FUNCIONARIO','koke gonzalez','14122021-1','abc','a',0,0,'','012',0,'2021-12-15','N','','N','','','2021-12-14 12:59:01',NULL,'',1,0,0,'','','2021-12-14 12:59:1','N');

/*Table structure for table `sys_empresa` */

DROP TABLE IF EXISTS `sys_empresa`;

CREATE TABLE `sys_empresa` (
  `IDEMPRESA` int NOT NULL AUTO_INCREMENT,
  `RUC` varchar(20) DEFAULT NULL,
  `RAZONSOCIAL` varchar(100) DEFAULT NULL,
  `DIRECCION` varchar(100) DEFAULT NULL,
  `TELEFONO` varchar(20) DEFAULT NULL,
  `IMAGEN` varchar(150) DEFAULT NULL,
  `DENOMINACION` varchar(50) DEFAULT NULL,
  `EMPLEADORNRO` varchar(20) DEFAULT NULL,
  `NROPATROMAJT` varchar(20) DEFAULT NULL,
  `USU_ALTA` int DEFAULT NULL,
  `FEC_ALTA` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `ESTADO` char(1) DEFAULT 'A',
  PRIMARY KEY (`IDEMPRESA`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Data for the table `sys_empresa` */

insert  into `sys_empresa`(`IDEMPRESA`,`RUC`,`RAZONSOCIAL`,`DIRECCION`,`TELEFONO`,`IMAGEN`,`DENOMINACION`,`EMPLEADORNRO`,`NROPATROMAJT`,`USU_ALTA`,`FEC_ALTA`,`ESTADO`) values 
(0,'000000','(NO/DEFINIDO)',NULL,NULL,NULL,NULL,NULL,NULL,0,'2021-11-25 12:37:26','A'),
(1,'012345','Odontologia',NULL,NULL,NULL,'Odontologia',NULL,NULL,0,'2021-11-25 12:38:29','A');

/*Table structure for table `sys_perfil` */

DROP TABLE IF EXISTS `sys_perfil`;

CREATE TABLE `sys_perfil` (
  `IDPERFIL` int NOT NULL AUTO_INCREMENT,
  `PERFIL` varchar(50) DEFAULT NULL,
  `IDMENU` int DEFAULT NULL,
  `ESTADO` varchar(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'A',
  PRIMARY KEY (`IDPERFIL`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

/*Data for the table `sys_perfil` */

insert  into `sys_perfil`(`IDPERFIL`,`PERFIL`,`IDMENU`,`ESTADO`) values 
(1,'ADMINISTRADOR',1,'A'),
(2,'FUNCIONARIO',1,'I'),
(3,'SECRETARIA/O',1,'A'),
(4,'PACIENTE',1,'A'),
(5,'MEDICO',1,'A');

/*Table structure for table `sys_usuario` */

DROP TABLE IF EXISTS `sys_usuario`;

CREATE TABLE `sys_usuario` (
  `IDUSUARIO` int NOT NULL,
  `IDPERSONA` int DEFAULT NULL,
  `USUARIO` varchar(100) DEFAULT NULL,
  `CLAVE` varchar(100) DEFAULT NULL,
  `ESTADO` varchar(1) DEFAULT 'A',
  `IDPERFIL` int DEFAULT NULL,
  `ESTADO_MIGRAR` varchar(2) DEFAULT 'NO' COMMENT '(NO - SE ESTA MIGRANDO) (SI - SE ESTA MIGRANDO)',
  `WEB` int DEFAULT '0' COMMENT 'Si es 1 (uno) es porque esta conectado o en-linea y si esta en 0 (cero) es porque no esta conectado o ha cerrado sesion',
  `EMAIL` varchar(100) DEFAULT NULL COMMENT 'CAMPO DONDE SE VA A GUARDAR EL EMAIL DONDE SE ENVIARA DATOS DEL USUARIO PARA REGISTRAR O RECUPERAR CUENTA',
  `CONFIR_EMAIL` varchar(2) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL COMMENT '(VALUES: SI / NO ) CAMPO PARA SABER SI EL USUARIO CONFIRMO SU CUENTA A TAVES DEL EMAIL QUE INGRESO POR MEDIO DE UN CODIGO QUE LE PASAMOS',
  PRIMARY KEY (`IDUSUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `sys_usuario` */

insert  into `sys_usuario`(`IDUSUARIO`,`IDPERSONA`,`USUARIO`,`CLAVE`,`ESTADO`,`IDPERFIL`,`ESTADO_MIGRAR`,`WEB`,`EMAIL`,`CONFIR_EMAIL`) values 
(0,1,'ROOT','ADMIN','A',1,'NO',1,NULL,'S'),
(1,5,'kgon','456','A',5,'NO',0,'a','NO');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
